//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Veiculoes = new HashSet<Veiculo>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string orgaoExpedidor { get; set; }
        public Nullable<decimal> rg { get; set; }
    
        public virtual ICollection<Veiculo> Veiculoes { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
