//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Pessoas = new HashSet<Pessoa>();
            this.Pecas = new HashSet<Peca>();
        }
    
        public int Id { get; set; }
        public string Endereco { get; set; }
    
        public virtual ICollection<Pessoa> Pessoas { get; set; }
        public virtual ICollection<Peca> Pecas { get; set; }
    }
}
