//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Montador
    {
        public Montador()
        {
            this.Veiculoes = new HashSet<Veiculo>();
            this.Pessoas = new HashSet<Pessoa>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> salario { get; set; }
    
        public virtual ICollection<Veiculo> Veiculoes { get; set; }
        public virtual ICollection<Pessoa> Pessoas { get; set; }
    }
}
