//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peca
    {
        public Peca()
        {
            this.PecadoVeiculoes = new HashSet<PecadoVeiculo>();
        }
    
        public int pecaId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Descricao { get; set; }
        public string numeroSerie { get; set; }
        public Nullable<System.DateTime> dataFabricacao { get; set; }
        public int FornecedorId { get; set; }
        public int FornecedorId1 { get; set; }
    
        public virtual ICollection<PecadoVeiculo> PecadoVeiculoes { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
