//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PecadoVeiculo
    {
        public PecadoVeiculo()
        {
            this.Veiculoes = new HashSet<Veiculo>();
        }
    
        public int pecadoVeiculo1 { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public string Quantidade { get; set; }
        public int Peca_pecaId { get; set; }
    
        public virtual ICollection<Veiculo> Veiculoes { get; set; }
        public virtual Peca Peca { get; set; }
    }
}
