//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Fornecedors = new HashSet<Fornecedor>();
            this.Montadors = new HashSet<Montador>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Cpf { get; set; }
    
        public virtual ICollection<Fornecedor> Fornecedors { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Montador> Montadors { get; set; }
    }
}
