//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int VeiculoId { get; set; }
        public string categoria { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int PecadoVeiculo_pecadoVeiculo1 { get; set; }
        public int MontadorId { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual PecadoVeiculo PecadoVeiculo { get; set; }
        public virtual Montador Montador { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
